spring:
  datasource:
    url: jdbc:h2:mem:maindb
  sql:
    init:
      mode: always
#      data-locations: R__insert_data.sql
#      schema-locations: V1__initial_schema.sql
  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true
  flyway:
    enabled: true