spring:
  application:
    name: realEstateClassifieds
  datasource:
    url: jdbc:postgresql://localhost:5430/realEstateClassifiedsDB
    username: usr
    password: pwd
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: true
    drop-first: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
  jpa:
    open-in-view: false
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG