spring:
  data:
    mongodb:
      uri: mongodb://mongoadmin:secret@localhost:27117
      database: book_library
  messages:
    encoding: UTF-8

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.hw.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local